leather-wallet/desktop

app/components/onboarding/onboarding-title.tsx
app/modals/receive-stx/receive-stx-modal.tsx
app/modals/transaction/transaction-form.tsx
app/modals/transaction/transaction-modal-layout.tsx
app/modals/transaction/transaction-modal.tsx
app/pages/home/home.tsx
app/pages/onboarding/01-welcome/welcome.tsx
app/pages/onboarding/08-set-password/set-password.tsx
package.json
yarn.lock

See commits, address many items of feedback jasper mentioned.

fix: jasper feedback

---

app/pages/onboarding/03-restore-wallet/restore-wallet.tsx

feat: add error for 12-word secret keys, closes #178

---

app/pages/onboarding/08-set-password/set-password.tsx

refactor: improve password flow

---

app/components/back-button.tsx
app/components/network-message.tsx
app/main.dev.ts
app/modals/reset-wallet/reset-wallet-modal.tsx
app/pages/app.tsx
app/pages/onboarding/01-welcome/welcome.tsx
app/pages/onboarding/04-connect-ledger/connect-ledger.tsx
app/pages/settings/settings.tsx
app/utils/disk-store.ts

feat: reset wallet

---

app/api/api.ts

Malformed url failing fallback pending tx polling operation

fix: pending tx not updating, closes #271

---

app/pages/onboarding/05-secret-key/secret-key.tsx

> [Download the latest builds](https://github.com/blockstack/stacks-wallet/actions/runs/329375657)
Updates copy per #275
Adjust copy slightly, assigning @markmhx for review

fix: add more grave description about losing key, closes #275

---

app/constants/index.ts
app/pages/onboarding/02-create-wallet/create-wallet.tsx

> [Download the latest builds](https://github.com/blockstack/stacks-wallet/actions/runs/337748626)
Adds a help link
Closes #248

feat: add trezor help link, closes #248

---

app/modals/upsert-stacks-node-api/upsert-stacks-node-api.tsx
package.json
yarn.lock

> [Download the latest builds](https://github.com/blockstack/stacks-wallet/actions/runs/337743763)
Removes unnecessary library for generating random strings.

refactor: remove uuid lib

---

app/api/watch-contract-execution.ts
app/modals/stacking/stacking-modal.tsx
configs/webpack.config.renderer.dev.babel.js

> [Download the latest builds](https://github.com/blockstack/stacks-wallet/actions/runs/341366799)
Bug fix with promise to catch stacking errors/completion

fix: stacking error not being caught

---

app/main.dev.ts
app/modals/transaction/transaction-modal.tsx
package.json
yarn.lock

> [Download the latest builds [4.0.0-beta.6]](https://github.com/blockstack/stacks-wallet/actions/runs/349454375).

fix: add text action context menu items

---

app/pages/home/home.tsx

> [Download the latest builds [4.0.0-beta.6]](https://github.com/blockstack/stacks-wallet/actions/runs/349955503).
Sorry about these issues, @timstackblock—some lines were merged that shouldn't have been yet

fix: tims form issues, closes #321, #322

---

app/components/chart/waffle-chart.tsx
app/components/home/stacking-begins-soon-card.tsx
app/package.json
app/pages/app.tsx
app/pages/home/home-layout.tsx
app/pages/home/home.tsx
app/store/stacking/stacking.actions.ts
app/store/stacking/stacking.reducer.ts
app/store/stacks-node/stacks-node.reducer.ts
app/utils/stacking/pox.ts
package.json
yarn.lock

> [Download the latest builds [4.0.0-beta.7]](https://github.com/blockstack/stacks-wallet/actions/runs/354464269).
Input welcome.
Not sure how to display/infer stacking details beyond a single cycle. If someone's on 8/12 cycles stacked. How is this displayed?

stacking progress visualisation/waffle chart

---

app/components/home/stacking-participation-card.tsx
app/components/home/stacking-promo-card.tsx
app/modals/stacking/stacking-modal.tsx
app/modals/stacking/steps/decrypt-wallet-form.tsx
app/modals/transaction/transaction-modal.tsx
app/pages/stacking/components/next-cycle-info.tsx
app/pages/stacking/components/stacking-form-step.tsx
app/pages/stacking/stacking.tsx
app/pages/stacking/step/choose-btc-address.tsx
app/pages/stacking/step/choose-cycles.tsx

> [Download the latest builds [4.0.0-beta.7]](https://github.com/blockstack/stacks-wallet/actions/runs/368312869).
Closes #339
Closes #341 
Closes #348
Closes #352

fix: various improvements

---

app/pages/onboarding/03-restore-wallet/restore-wallet.tsx

> [Download the latest builds [4.0.0-beta.7]](https://github.com/blockstack/stacks-wallet/actions/runs/385088953).

feat: allow 12-word phrases, closes #253

---

README.md

> [Download the latest builds [4.0.0-beta.8]](https://github.com/blockstack/stacks-wallet/actions/runs/400582087).
Updates badge with new branch details

fix(readme): update with new build info

---

.github/workflows/typecheck.yml
app/components/home/stacking-card.tsx
app/pages/onboarding/03-restore-wallet/restore-wallet.tsx
app/store/address/address.reducer.ts
app/store/configureStore.dev.ts
app/store/configureStore.prod.ts
package.json
tsconfig.json
yarn.lock

> [Download the latest builds [4.0.0-beta.8]](https://github.com/blockstack/stacks-wallet/actions/runs/409030158).
Run type check on ci, fix type errors, add skipLibCheck.

ci: run ts compiler

---

.github/workflows/stacks-wallet.yml
app/constants/routes.json
app/pages/onboarding/00-terms/terms.tsx
app/pages/onboarding/index.ts
app/routes.tsx
package.json

> [Download the latest builds](https://github.com/blockstack/stacks-wallet/actions/runs/424069982).
This will be version  when merged into `master`

feat: terms screen, closes #171

---

package.json

> [Download the latest builds](https://github.com/blockstack/stacks-wallet/actions/runs/436048734).
> [Download the latest builds](https://github.com/blockstack/stacks-wallet/actions/runs/437790667).
> [Download the latest builds](https://github.com/blockstack/stacks-wallet/actions/runs/437794682).
This will be version  when merged into `master`

fix: add in beta branch

---

app/pages/onboarding/03-restore-wallet/restore-wallet.tsx

> [Download the latest builds](https://github.com/blockstack/stacks-wallet/actions/runs/436673597).
> [Download the latest builds](https://github.com/blockstack/stacks-wallet/actions/runs/436690560).
This will be version  when merged into `master`
Force lowercase seed phrase input validation

fix: force lowercase seedphrase input

---

SECURITY.md

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/440032450)
Adds `SECURITY.txt` to repo

Feat/add security.txt

---

app/constants/index.ts
app/pages/onboarding/00-terms/terms.tsx

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/440388862)
Updates Terms of Service

feat: update Terms of Service, closes #171

---

app/pages/onboarding/03-restore-wallet/restore-wallet.tsx

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/450771136)

fix: remove 24 word phrasing, closes #427

---

electron-builder.js
package.json
yarn.lock

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/460852579)
Update Ledger app with changes that unbreak Ledger signing

fix: ledger signing, closes #432 #433

---

app/components/testnet/exchange-withdrawal-warning.tsx
app/modals/receive-stx/receive-stx-modal.tsx

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/463949598)

feat: provide testnet wallet warnings

---

app/environment.ts

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/469784412)
Was already fixed in `feat/show-mempool-txs` but will merge first

fix: mainnet addresses

---

.github/workflows/audit.yml
.github/workflows/debug-build.yml
.github/workflows/exact-versions.yml
.github/workflows/publish-version.yml
.github/workflows/typecheck.yml
app/hooks/use-check-for-updates.ts
electron-builder.js
scripts/notarize.js

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/473928213)
Adjust logic to look for v4 and above.

fix: issue with mainnet update available

---

.github/workflows/publish-version.yml
app/main.dev.ts
app/pages/onboarding/07-set-password/set-password.tsx
electron-builder.js

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/474096464)

fix: up a nice icon for Bill Gates

---

app/crypto/validate-password.ts
app/pages/onboarding/07-set-password/set-password.tsx

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/474390973)

feat: don't allow Secret Key as password

---

.github/workflows/debug-build.yml
.github/workflows/publish-version.yml
app/constants/index.ts
app/hooks/use-check-for-updates.ts

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/475473076)

fix: update logic

---

app/components/home/stacking-card.tsx
app/pages/stacking/step/choose-btc-address.tsx
app/utils/stacking.spec.ts
app/utils/stacking.ts

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/474670119)

feat: support formatting testnet addresses, closes #469

---

app/pages/stacking/components/next-cycle-info.tsx
app/pages/stacking/components/stacking-info-card.tsx
app/pages/stacking/components/stacking-terms.tsx
app/pages/stacking/stacking.tsx
app/pages/stacking/step/choose-cycles.tsx
app/store/stacking/stacking.reducer.ts

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/475640465)

fix: improve timing communication, closes #470

---

.github/workflows/audit.yml
.github/workflows/create-version.yml
.github/workflows/debug-build.yml
.github/workflows/exact-versions.yml
.github/workflows/publish-version.yml
.github/workflows/typecheck.yml

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/475760051)

chore: update ci

---

.github/workflows/debug-build.yml
.github/workflows/exact-versions.yml
.github/workflows/publish-version.yml
app/app-dev.html
app/app.html
app/components/beta-notice.tsx
app/components/home/transaction-list/transaction-list-error.tsx
app/components/title-bar/title-bar.tsx
app/constants/index.ts
app/crypto/key-generation.spec.ts
app/index.tsx
app/main.dev.ts
app/main/get-user-data-path.ts
app/modals/transaction/transaction-modal.tsx
app/package.json
app/pages/home/home.tsx
app/pages/onboarding/04-connect-ledger/connect-ledger.tsx
app/preload.ts
app/store/configureStore.ts
app/store/stacking/stacking.reducer.ts
app/types/index.ts
app/utils/stacking.ts
configs/webpack.config.base.js
configs/webpack.config.main.prod.babel.js
configs/webpack.config.renderer.dev.babel.js
configs/webpack.config.renderer.prod.babel.js
electron-builder.js
jest.config.js
package.json
yarn.lock

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/478747849)
Closes #296

fix: show error step on Ledger error, closes #296

---

app/main.dev.ts
app/main/get-user-data-path.ts
app/pages/stacking/components/stacking-form-step.tsx
app/pages/stacking/stacking.tsx
app/pages/stacking/step/choose-amount.tsx
app/pages/stacking/step/choose-btc-address.tsx
app/pages/stacking/step/choose-cycles.tsx
app/pages/stacking/step/confirm-and-lock.tsx
package.json

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/479997134)
@markmhx This one's for you. Can you please test? 🙏🏼

feat: improve stacking flow, closes #343

---

electron-builder.js

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/480235744)

fix: install set up

---

app/main.dev.ts
app/pages/onboarding/05-secret-key/secret-key.tsx
app/store/keys/keys.reducer.spec.ts
app/store/keys/keys.reducer.ts
package.json
yarn.lock

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/480354645)

chore: remove electron-log

---

electron-builder.js
package.json
resources/entitlements.mac.plist
yarn.lock

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/482896448)
re issue https://github.com/node-hid/node-hid/issues/321

fix: code signing breaking ledger integration

---

app/hooks/use-ledger.ts
app/pages/onboarding/00-terms/terms.tsx
app/pages/onboarding/04-connect-ledger/connect-ledger.tsx

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/483297481)

fix: improve ledger error messaging

---

app/hooks/use-ledger.ts
app/main.dev.ts
app/pages/onboarding/00-terms/terms.tsx
app/preload.ts

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/485233938)

fix: close wallet on terms reject

---

app/package.json
app/pages/onboarding/02-create-wallet/create-wallet.tsx
app/pages/onboarding/04-connect-ledger/connect-ledger.tsx
app/yarn.lock

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/485704729)

fix: handle error case if mainnet wallet attempted to generate testnet

---

app/package.json
app/yarn.lock

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/486318021)
Should fix failed transaction signing

fix(transactions): failed fee estimation

---

app/hooks/use-ledger.ts

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/487536150)

fix(ledger): increase polling time

---

app/pages/onboarding/03-restore-wallet/restore-wallet.tsx

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/487767640)

chore: hide Ledger for testnet, closes #510

---

app/modals/transaction/steps/decrypt-wallet-form.tsx
app/modals/transaction/steps/sign-tx-with-ledger.tsx
app/modals/transaction/transaction-modal.tsx

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/488039099)

fix: tx flow error handling

---

app/constants/index.ts
app/hooks/use-check-for-updates.ts
app/hooks/use-mempool.ts
app/pages/app.tsx
app/store/stacking/stacking.reducer.ts

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/488112874)

fix: handle failed requests better

---

app/components/back-button.tsx
app/components/title-bar/title-bar.tsx
app/hooks/use-back-url.ts
app/pages/onboarding/07-set-password/set-password.tsx
app/pages/root.tsx

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/494205718)

fix: break out hooks a bit more

---

app/components/back-button.tsx
app/components/title-bar/title-bar.tsx
app/hooks/use-back-url.ts
app/pages/onboarding/03-restore-wallet/restore-wallet.tsx
app/pages/onboarding/07-set-password/set-password.tsx
app/pages/root.tsx

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/494308376)

fix: improve flow of typing in phrase, closes #526

---

app/constants/index.ts

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/495563618)

chore: update Blockstack --> Hiro Systems

---

app/pages/home/home.tsx

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/491397297)

fix: confirmed & mempool txs showing at same time

---

app/components/tooltip.tsx
app/components/wallet-warning.tsx
app/pages/home/home-layout.tsx
app/pages/onboarding/03-restore-wallet/restore-wallet.tsx
app/pages/onboarding/07-set-password/set-password.tsx

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/495682591)

chore(copy): added some tooltips to onboarding

---

app/modals/stacking/stacking-modal.tsx

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/512686849)
Now only adjusts stacking amount with the stacking libraries `modifyLockTxFee()` method, when the amount stacked is equal to, or within 1000 usTX of the address' balance.
Along with tx modal, stacking modal needs to be refactored.

fix: stacking fee adjustment

---

README.md

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/625046871)
This PR tries to improve a bit the installing instructions and adds a link to our test coverage.
@kyranjamie can you please review if this is written in the queen's English?

Chore: update the readme file

---

.github/workflows/audit.yml
app/components/home/stacking-card.tsx
app/pages/stacking/direct-stacking/components/choose-cycles.tsx
app/pages/stacking/direct-stacking/direct-stacking.tsx

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/661429476)

chore: remove hardcoded cycle time, closes #636

---

app/hooks/use-balance.ts
app/hooks/use-mempool.ts
app/pages/app.tsx
app/pages/home/home.tsx
app/utils/sum-stx-tx-total.ts
app/utils/tx-utils.spec.ts
app/utils/tx-utils.ts

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/663885882)
Closes #591
Closes #657
https://user-images.githubusercontent.com/1618764/111483163-d8c88080-8734-11eb-8749-9cb50131fc40.mp4

fix: subtract spent balances from total

---

app/api/api.ts

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/679482154)
Adds two headers to HTTP requests stating app name and version.
Closes #700

chore: add headers to all requests

---

app/pages/stacking/delegated-stacking/components/choose-membership-duration.tsx

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/683193949)
Change copy to explain indefinite better.

chore: make indefinite definition clearer

---

app/components/home/delegation-card.tsx
app/constants/index.ts
app/hooks/use-calculate-fee.ts
app/hooks/use-fetch-fee-rate.ts
app/models/index.ts

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/686217121)
Closes #649
https://user-images.githubusercontent.com/1618764/111765284-7b534180-88a4-11eb-9236-fbc4d039d0d5.mp4

fix: prohibit revocation when 0 STX balance, closes #649

---

electron-builder.js

> _Currently building new release, please wait for the latest_&nbsp; <img src="https://user-images.githubusercontent.com/1618764/97873036-51dfb200-1d17-11eb-89f5-0a922dc3ac92.gif" width="12" />

fix: support windows 7

---

app/app-dev.html
app/app.html
app/components/color-mode-button.tsx
app/components/home/delegation-card.tsx
app/hooks/use-listen-system-theme-change.ts
app/main.dev.ts
app/main/register-theme-mode-handlers.ts
app/pages/app.tsx
app/pages/settings/settings.tsx
app/preload.ts

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/788642362)
By default, the theme will follow the user's system preference. If they choose a theme, it will the stick to that theme, regardless of system pref, until reverting back to system theme in settings.
https://user-images.githubusercontent.com/1618764/116214034-9b4d0f00-a746-11eb-8fee-a7f2cf18ce11.mp4

Update theme with system color preference

---

app/hooks/use-global-polling.ts
app/hooks/use-watch-stacking-tx.ts
app/hooks/use-websocket-integration.ts
app/pages/app.tsx
app/store/stacking/stacking.reducer.ts

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/816873354)
Move inline effects out of `<App />`

refactor: global app hooks

---

.github/workflows/gh-pages.yml
README.md
jest.config.js

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/884990727)
Wanted to add the mega super fun generated coverage badge, as per web wallet

chore: add fun coverage badge

---

README.md
app/components/home/transaction-list/transaction-list-item-mempool.tsx

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/921510189)

chore: put badges on one line

---

app/modals/receive-stx/components/address-displayer.tsx

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/949831626)
Closes #571

fix: add memo not needed warning

---

.github/workflows/debug-build.yml

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/985786894)

ci: forks should create test builds

---

.github/stale.yml

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/1015159786)

chore: 3 years until stale

---

app/components/home/delegation-card.tsx
app/store/stacking/stacking.reducer.ts

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/1004186106)
Related #847.
Contributed by @hd-o 
Pushing up changes here as CI isn't working

fix: round stacking percentage, closes #837

---

app/package.json
app/yarn.lock
package.json
yarn.lock

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/1022647885)
Thanks to contributor @jenkijo for these changes 🥳

chore: upgrade packages

---

app/hooks/use-prepare-ledger.ts
app/modals/receive-stx/components/reveal-stx-address-ledger.tsx

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/1022953106)
Copy changes to guide users for Ledger upgrade

chore: update copy of ledger err

---

README.md

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/1026736019)

chore(readme): vscode badge

---

.github/workflows/integration-tests.yml
package.json
yarn.lock

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/1221404325)
Update axios

fix: update axios library

---

.github/workflows/create-version.yml
.github/workflows/gh-pages.yml
.github/workflows/publish-version.yml
package.json

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/1221730595)
lsdjkflsdjf

chore: update to use main branch

---

.github/workflows/debug-build.yml
app/package.json
app/yarn.lock
electron-builder.js
resources/libusbK.dll

> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/1237548353)
Fixes DLL bundling issue Windows

fix(windows): add dll signing to build config

---

.github/workflows/debug-build.yml
.github/workflows/publish-version.yml
app/hooks/use-analytics.ts
app/modals/receive-stx/components/address-displayer.tsx
app/modals/reset-wallet/reset-wallet-modal.tsx
app/modals/send-stx/send-stx-modal.tsx
app/modals/send-stx/steps/transaction-form.tsx
app/pages/home/home.tsx
app/pages/onboarding/04-restore-wallet/restore-wallet.tsx
app/pages/onboarding/06-secret-key/secret-key.tsx
app/pages/onboarding/07-verify-key/verify-key.tsx
app/pages/onboarding/08-set-password/set-password.tsx
app/routes.tsx
app/utils/init-segment.ts
configs/webpack.config.base.js
package.json
yarn.lock

> [Download the latest build](https://github.com/hirosystems/stacks-wallet/actions/runs/1465883439)
Use the following template to create your pull request
This adds segment integration with all the main tracking event see #928 
- [X ] New feature
No
Just use the wallet and the relevant event shall appear in the segment app console. 
@kyranjamie @fbwoolf 
(Draft so we don't merge it into release)

Feat/add segment/i928

---

app/modals/send-stx/send-stx-modal.tsx

> [Download the latest build](https://github.com/hirosystems/stacks-wallet/actions/runs/1525535907)
Noticed a bug in the wallet where, on clicking send max and going to the next screen, an error is shown as the amount + fee > available balance. 
This PR fixes the fee calculation used in the send max logic, so this doesn't happen. 
QA: ensure the send max button functionality works correctly.

fix(send-form): incorrect fee calc in send max button

---

.github/workflows/integration-tests.yml
app/constants/index.ts

> [Download the latest build](https://github.com/hirosystems/stacks-wallet/actions/runs/1563925278)
run tests with custom url

ci: run from custom url

---

.github/workflows/audit.yml
.github/workflows/create-version.yml
.github/workflows/debug-build.yml
.github/workflows/exact-versions.yml
.github/workflows/gh-pages.yml
.github/workflows/integration-tests.yml
.github/workflows/publish-version.yml
.github/workflows/typecheck.yml
app/main.dev.ts
app/tests/features/onboarding.feature.ts

> [Download the latest build](https://github.com/hirosystems/stacks-wallet/actions/runs/3574905179)
This PR fixes build issues that've creeped in during the last year without release.

ci: fix the build 

---

README.md
app/pages/stacking/direct-stacking/components/direct-stacking-intro.tsx

> [Download the latest build](https://github.com/hirosystems/stacks-wallet/actions/runs/3649061737)
In fixing the typo, documented steps needed to run the app on Ubuntu.
Closes #1109

Fix typo & add docs for ubuntu

---

README.md
app/hooks/use-analytics.ts
app/utils/init-segment.ts
package.json
yarn.lock

> [Download the latest build](https://github.com/hirosystems/stacks-wallet/actions/runs/3845876400)
Closes https://github.com/hirosystems/stacks-wallet/issues/1117

fix analytics in production

---

app/package.json
app/yarn.lock

Clone of @friedger's PR
This PR
upgrades stacks dependencies in app/package.json
fixes https://github.com/hirosystems/desktop-wallet/issues/1182

chore: upgrade stacks dependencies (1182)

---

package.json
yarn.lock

> [Download the latest build](https://github.com/leather-wallet/desktop/actions/runs/6261676390)
Update electron packages

refactor: upgrade electron 24

---

SECURITY.md
app/components/home/transaction-list/transaction-list-error.tsx
app/components/legal-disclaimer-tooltip.tsx
app/components/request-diagnostics.layout.tsx
app/main/get-user-data-path.ts
app/menu.ts
app/package.json
app/pages/stacking/delegated-stacking/components/delegated-stacking-terms.tsx
app/routes.tsx
app/store/stacks-node/stacks-node.reducer.ts
app/yarn.lock
electron-builder.js
package.json

> [Download the latest build](https://github.com/leather-wallet/desktop/actions/runs/6496653843)
Fix Hiro references

chore: remove hiro references

---

.github/workflows/debug-build.yml
.github/workflows/publish-version.yml
electron-builder.js

> [Download the latest build](https://github.com/leather-wallet/desktop/actions/runs/6627055827)
Removing WIndows code signing because of certificate expiry

chore: remove win code signing

---

.github/workflows/debug-build.yml
.github/workflows/publish-version.yml
CHANGELOG.md
SECURITY.md
app/components/home/transaction-list/transaction-list-error.tsx
app/components/legal-disclaimer-tooltip.tsx
app/components/request-diagnostics.layout.tsx
app/main/get-user-data-path.ts
app/menu.ts
app/package.json
app/pages/onboarding/00-terms/terms.tsx
app/pages/stacking/delegated-stacking/components/delegated-stacking-terms.tsx
app/routes.tsx
app/store/stacks-node/stacks-node.reducer.ts
app/yarn.lock
electron-builder.js
package.json
yarn.lock

> [Download the latest build](https://github.com/leather-wallet/desktop/actions/runs/6641133476)
Electron security patches, copy fixes
- Closes #1235
- Closes #1232
- Closes #1234

Copy updates Electron

---

app/components/home/stacking-promo-card.tsx

> [Download the latest build](https://github.com/leather-wallet/desktop/actions/runs/9077963616)
Add the URL

fix: direct to lockstacks
