- app/common/lib/index.js
- app/components/field/index.js
- app/components/loading/index.js
- app/components/transaction-list/index.js
- app/containers/balance/index.js
- app/containers/modals/receive.js
- app/containers/modals/send.js
- app/containers/modals/send/initial.js
- app/containers/modals/send/top-up.js
- app/containers/modals/settings.js
- app/containers/modals/software-warning.js
- app/containers/modals/tx-fees-top-up.js
- app/screens/dashboard/index.js
- app/screens/onboarding/confirm-seed/index.js
- app/screens/onboarding/initial/index.js
- app/screens/onboarding/new-seed/index.js
- app/screens/onboarding/new/index.js
- app/screens/onboarding/restore-seed/index.js
- app/screens/onboarding/restore/index.js
- app/screens/onboarding/watch-only/index.js
- app/store/actions/wallet.js
This started with a base of `feature/software-wallet` per @yknl. Implemented changes approved in @markmhx  with some modifications. Includes:
- seed phrase > passphrase
- sentence case on all headings
- using same address balance language as appears in explorer where possible
- some other modifications to language to support 24 word and reinforce passphrase security
Build and run to see all changes of course. Key dialogs:
Signed-off-by: Mary Anthony <mary@blockstack.com>
> Updating with language from the design

- app/containers/modals/settings.js
- app/containers/modals/tx-fees-top-up.js
- app/store/actions/wallet.js
Adds clarifying language to settings.
Also to the pop-up
Signed-off-by: Mary Anthony <mary@blockstack.com>
> Clarify cost basis fixes #90

- app/common/constants.js
- app/common/lib/transactions.js
- app/components/transaction-item/index.js
- app/containers/balance/index.js
- app/preload.js
- app/screens/dashboard/index.js
- app/screens/onboarding/initial/index.js
- app/store/actions/wallet.js
- app/store/reducers/app.js
- app/store/reducers/notifications.js
- app/store/selectors/app.js
- package-lock.json
- package.json
This PR adds a check for the Stacks blockchain version the connected core node is running. It will disable the sending of transactions when the core node is running a newer and incompatible version of the Stacks blockchain.
Also fixes a problem where no error message is displayed when there isn't enough BTC in the fuel address.
Warning message to update the Stacks wallet.
> Add blockchain version compatibility check 

- app/crypto/key-encryption.ts
- app/crypto/key-generation.spec.ts
- app/crypto/key-generation.ts
- app/crypto/validate-password.spec.ts
- app/package.json
- app/pages/onboarding/08-set-password/set-password.tsx
- app/store/keys/keys.actions.ts
- app/yarn.lock
This PR removes blockstack.js as a dependency, and uses the Web Crypto API directly, in order to use `AES-CBC-256`.
> feat: use webcrypto/aes-cbc-256, remove blockstack.js dep

- app/package.json
- app/utils/stacking/pox.spec.ts
- app/utils/stacking/pox.ts
- app/yarn.lock
> [Download the latest builds](https://github.com/blockstack/stacks-wallet/actions/runs/302227080)
[I think I need to rebase, but onto which branch? `release/stacking`? @kyranjamie feel free to massage or cherry pick my one commit from this PR, put it into your own branch, etc.]
I've added a small utility for interacting with `pox.clar`, the core contract for stacking. You can:
- Lock some STX
- Query the state for a stacker
I've only tested this against a local core node and sidecar. For the sidecar, I'm using https://github.com/blockstack/stacks-wallet/pull/257. For the core node, I'm using `feat/pox-devx`, but with some tweaks:
This in the `Stacks.toml` file:
```toml
[[mstx_balance]]
address = "STB44HYPYAT2BB2QE513NSP81HTMYWBJP02HPGK6"
amount = 1000000000000000000
[[mstx_balance]] …
```
> Feat: small library for interacting with pox.clar

- app/containers/balance/index.js
- app/containers/modals/withdraw/initial.js
- app/preload.js
- app/screens/onboarding/initial/index.js
- app/store/actions/wallet.js
- app/store/selectors/wallet.js
- app/utils/stacks.js
- app/utils/utils.js
- app/utils/validation.js
- package.json
This PR fixes a bug where invalid STX transactions (valid BTC transaction but rejected by Stacks core node) shows up as a valid STX transaction in the wallet transaction history. This only occurs when the account has no prior transaction history. Fixed by updating to `@blockstack/stacks-utils@0.1.6` https://github.com/blockstack/stacks-utils/pull/17
No
No
Invalid transactions should not show up as valid in history.
> fix: invalid tx showing up as valid

- app/components/home/balance-card.tsx
- app/pages/home/home.tsx
- app/store/address/address.reducer.ts
> [Download the latest builds](https://github.com/blockstack/stacks-wallet/actions/runs/329056707)
This PR introduces as new selector what subtracts the stacked amount from the available balance.
> fix: presenting available balance when stacking, closes #287

- .github/workflows/audit.yml
- .github/workflows/build-release-prod.yml
- .github/workflows/build-release.yml
- .github/workflows/build.yml
- .github/workflows/commitlint.yml
- .github/workflows/exact-versions.yml
- .github/workflows/lint.yml
- .github/workflows/test.yml
- app/api/api.ts
- app/components/beta-notice.tsx
- app/components/home/balance-card.tsx
- app/package.json
- app/pages/home/home.tsx
- configs/webpack.config.base.js
- configs/webpack.config.main.prod.babel.js
- configs/webpack.config.renderer.dev.babel.js
- configs/webpack.config.renderer.prod.babel.js
- package.json
> [Download the latest builds [4.0.0-beta.6]](https://github.com/blockstack/stacks-wallet/actions/runs/341854605).
That's the last time I use vscode built-in git. Checked out this pr blockstack/stacks-wallet#303 it the branch via git panel, had only a single commit with the entire tree in it, so a commit amend gone done broked stuff 🤔 🥴
This PR makes some changes to the CI task and adds some (very) simple error handling for faucet, and only sends a stacking faucet request when clicking the button while holding <kbd>alt</kbd>
> feat: revert to using normal faucet

- app/api/api.ts
- app/constants/index.ts
- app/main.dev.ts
- app/modals/transaction/transaction-modal.tsx
> [Download the latest builds](https://github.com/blockstack/stacks-wallet/actions/runs/337617551)
This PR changes the fee estimation logic used in the UI to:
1) Display estimated transaction fee information
2) Calculate the maximum spend by subtracting fee from balance
Previous implementation created a fake transaction with hardcoded values (the user may not have entered an address when choosing to send their entire balance), and used the fee value estimated internally. This was not ideal as an auditor of the code may rightly question "Who the hells address is that?"
This change uses a hard coded stx transaction size value, as a STX transaction is always 180bytes, and uses this as the basis for the fee estimation.
Hoping for reviews from one of @reedrosenbluth @yknl @aulneau @hstove …
> refactor: fee estimation logic

- app/utils/external-links.ts
- package.json
- yarn.lock
> [Download the latest builds [4.0.0-beta.7]](https://github.com/blockstack/stacks-wallet/actions/runs/355871321).
Proactively validate urls being opened externally. 
These can be added by a user in one instance (when defining a custom node). These are validated upon entry, but this acts as an extra layer of protection.
> feat: dbl check urls being opened

- app/pages/onboarding/07-set-password/set-password.tsx
> [Download the latest builds [4.0.0-beta.7]](https://github.com/blockstack/stacks-wallet/actions/runs/393883340).
Adjusted the password messaging to avoid circumstance where we advise someone to use a 12 char pw when they already are.
I think what we have now works quite well. zxcvbn library provides a handful of useful warnings if you're using a useless password, and we have generic guidance if it doesn't meet the criteria and there's no suggestions.
> fix: use clearer password messaging, closes #260

- app/pages/stacking/step/choose-btc-address.tsx
- package.json
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/460758495)
This PR changes validation logic so that testnet BTC addresses are only prohibited in mainnet mode. This follows a change to the PoX contract that handles mainnet/testnet behaviours differently.
> fix(stacking): allow testnet btc address in testnet mode

- app/main.dev.ts
- app/main/validate-config.ts
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/476054810)
This is a bit of an edge case, but that could result in a loss of wallet data.
Consider a user that loses their seed phrase, and only has the config.json as their backup. They go and find the config file, accidentally delete 1 char rendering it invalid JSON and load the wallet.
Improbable though that might be, the wallet currently just wipes the file. This'd be fine if you have your seed phrase, but if you don't you'd lose your only remaining copy. The wallet should never delete a config like this, even if invalid.
See implementation, but this basically first checks if the JSON is valid, if not, makes a back up. Store will then parse and wipe that file.
@timstackblock or @markmhx would really …
> fix: wiping a corrupt wallet file

- app/constants/index.ts
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/487678718)
> fix: change default core node url, closes #507

- app/components/home/balance-card.tsx
- app/components/title-bar/network-message.tsx
- app/constants/index.ts
- app/environment.ts
- app/hooks/use-check-for-updates.ts
- app/modals/receive-stx/receive-stx-modal.tsx
- app/modals/stacking/stacking-modal.tsx
- app/modals/transaction/transaction-modal.tsx
- app/pages/onboarding/02-create-wallet/create-wallet.tsx
- app/pages/onboarding/04-connect-ledger/connect-ledger.tsx
- app/pages/stacking/step/choose-btc-address.tsx
- app/store/stacking/stacking.actions.ts
- app/utils/network-utils.ts
- configs/webpack.config.base.js
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/488058744)
I realised yesterday how all the `if network then x or y` logic is quite unsafe. If `STX_NETWORK` were mistakenly set to something other than `mainnet` or `testnet`, much of the logic would still function in the case of `if (NETWORK !== 'testnet')`.
This PR explicitly checks for a version type, provides a helper method, and throws if it's neither.
> refactor: safter network switching logic

- app/modals/transaction/steps/failed-broadcast-error.tsx
- app/modals/transaction/transaction-modal.tsx
- app/store/transaction/transaction.actions.ts
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/494402188)
Noticed some unusual behaviours with `safeAwait` not resolving when there's an error, using try/catch
Can be made prettier but makes it clear for now.
> chore: include api errors

- app/constants/index.ts
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/512951791)
From @jessesoslow 
> small note: i just clicked the "buy stacks" button in the wallet and the page doesn't load.  looks like coinmarketcap has changed the Stacks token listing from Blockstack to Stacks.  So the URL needs to be updated to https://coinmarketcap.com/currencies/stacks/
Updating the coinmarketcap URL to fix this.
> fix: update coinmarketcap Stacks URL

- .github/workflows/gh-pages.yml
- .gitignore
- jest.config.js
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/617024632)
Adds a GH workflow that will generate and push up code coverage reports in the `gh-pages` branch to be displayed via GH pages. Since this is being committed to the `gh-pages` branch, it shouldn't interfere with the Semantic Versioning step or any other workflows which trigger from pushes to the `master` branch.
Once this is merged, we can turn on GH Pages in the repo settings.
Part of https://github.com/blockstackpbc/devops/issues/642
No.
> chore: gh pages code coverage reports

- .github/workflows/gh-pages.yml
- .gitignore
- jest.config.js
> _Currently building new release, please wait for the latest_&nbsp; <img src="https://user-images.githubusercontent.com/1618764/97873036-51dfb200-1d17-11eb-89f5-0a922dc3ac92.gif" width="12" />
Ideally the coverage report would show on the root page of this repo's GH pages. Currently it does not. These changes will adjust that in order to reach this outcome.
> chore: adjust coverage dir and publish step

- app/components/error-label.tsx
- app/components/home/delegation-card.tsx
- app/hooks/use-delegation-status.ts
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/679023477)
This PR adds a warning when a user's delegation `until-burn-ht` argument is less than the current burn height. Without this warning, users are led to believe they have an active delegation (which technically they do), but one that prohibits any further stacking on their behalf.
Closes #691
> fix(stacking): show dead delegation error, closes #691

- app/components/home/balance-card.tsx
- app/hooks/use-balance.ts
- app/pages/home/home.tsx
- app/store/address/address.reducer.ts
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/719508754)
Bug was caused by locked amount being subtracted twice. Had missed this old in-component code that was re-calculating the locked/total.
Refactored to only use values via hook.
> fix: available balance calculation

- app/main/register-store-handlers.ts
- app/pages/settings/settings.tsx
- app/preload.ts
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/763943906)
Open to suggestions as to better ways to display this better, but the wallet should really show where it's data is.
> fix: display where wallet's data is

- .github/workflows/typecheck.yml
- app/main.dev.ts
- app/main/register-ledger-listeners.ts
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/763960478)
Closes #723
Fixes issue where new listeners are created when closing/opening main window on macOS
> fix(ledger): prevent errors when closing macOS window

- app/modals/send-stx/send-stx-modal.tsx
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/812833558)
@yknl I was unable to replicate [the issue you mentioned on Discord](https://discord.com/channels/621759717756370964/745197302255321108/839258638097973278), but I have a feeling it may have been related to an unhandled error.
This change wraps the suspected-failing call in `safeAwait`, a method that catches any error, allowing the promise to proceed and, subsequently, close the modal.
> fix: send stx modal not closing

- app/main/register-theme-mode-handlers.ts
- app/preload.ts
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/816807633)
Fixes bug on macoS where exception is thrown when system theme changes, and the window is closed.
Solution is to add/remove handlers based on window creation.
> fix(theme): handle theme change during closed window

- app/modals/send-stx/send-stx-modal.tsx
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/827389652)
The form isn't resetting on all close handlers.
Related blockstack/ui#107
> fix: send stx form not resetting

- app/components/tx-signing/sign-transaction-ledger.tsx
- app/constants/index.ts
- app/hooks/use-fetch-account-nonce.ts
- app/hooks/use-prepare-ledger.ts
- app/pages/onboarding/04-connect-ledger/connect-ledger.tsx
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/857196822)
This PR introduces the hard coded version number of the latest Stacks Ledger app. By pinning this version to the next release, we can ensure no breaking changes when the newer one is released, at which time we'll amend this behaviour to support the latest version.
> fix(ledger): ledger app version handling

- app/modals/send-stx/send-stx-modal.tsx
- app/modals/send-stx/steps/transaction-form.tsx
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/871058139)
I've seen many reports of this lately so thought it worth trying to work in a fix.
An explicit confirmation when **no memo is needed** seems to be the most common pattern when withdrawing/depositing memo-using currencies, STX, XLM etc. I haven't given much thought to the exact messaging, so please leave feedback.
Closes #571 
https://user-images.githubusercontent.com/1618764/118469334-e6cf5900-b705-11eb-8c7e-6bac4e84e4b1.mp4
> fix: add memo warning to prevent user error, closes #571

- app/modals/send-stx/send-stx-modal.tsx
- app/modals/send-stx/steps/transaction-form.tsx
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/877712347)
Fixes form validation bug reported by @Eshwari007 🎉  
Closes #815.
I don't fully recall why I added this send max handling behaviour. Nonetheless, it's the cause of randomly throwing validation error so safe to remove.
> fix(stx-form): validation error throwing inaccurately, closes #815

- app/modals/components/base-modal.tsx
- app/modals/components/modal-header.tsx
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/881337242)
Closes #824
Ensures modals have overflow when on low viewport display.
> chore: add overflow to modal

- README.md
- app/components/home/transaction-list/transaction-list.tsx
- app/store/transaction/transaction.reducer.ts
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/1029533728)
This PR adds a conditions then ensures the "cannot load tx list" state is only shown when there are no cached txs.
Currently, if the endpoint fails intermittently, the wallet will toggle between the list and the error state (bad ux)
> fix(home): use cached txs as fallback when endpoint fails

- README.md
- app/hooks/use-mempool.ts
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/1030303976)
User reported issue with hanging pending txs. These were mempool txs with status `dropped_stale_garbage_collect`.
This PR filters them, as only `pending` txs should be shown.
> fix(home): only show 'tx_status' pending mempool txs

- .github/workflows/create-version.yml
- .github/workflows/debug-build.yml
- .github/workflows/publish-version.yml
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/1038412890)
Six months in the making, this PR is ready for review LOL
- Automates addition of the release notes & sha256 sums
- Wraps shasums in gpg armour
> chore(ci): add verified sha256 hashes for release assets, closes #515

- .github/workflows/publish-version.yml
- README.md
- app/components/version-info.tsx
- app/hooks/use-prepare-ledger.ts
- app/main.dev.ts
- app/main/macos-touchbar-menu.ts
- app/menu.ts
- app/package.json
- app/pages/onboarding/00-terms/terms.tsx
- app/pages/onboarding/01-welcome/welcome.tsx
- app/pages/onboarding/03-restore-wallet/restore-wallet.tsx
- app/pages/onboarding/05-secret-key/secret-key.tsx
- electron-builder.js
- package.json
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/1046077023)
This PR updates the wallet name to `Hiro Wallet`.
> refactor: change to hiro wallet branding

- app/api/api.ts
> [Download the latest build](https://github.com/blockstack/stacks-wallet/actions/runs/1218194054)
I have no idea why this was a post. Did the API once return from POSTs?
> feat: use a get to check status

- .github/workflows/debug-build.yml
> [Download the latest build](https://github.com/hirosystems/stacks-wallet/actions/runs/1411623759)
Doh. It was just missing the env var in debug 🤦🏼
> test: sentry in debug build

- resources/entitlements.mac.plist
> [Download the latest build](https://github.com/hirosystems/stacks-wallet/actions/runs/1615444279)
Removes an unnecessary entitlement https://developer.apple.com/documentation/bundleresources/entitlements/com_apple_security_cs_allow-dyld-environment-variables 
This was originally added around mainnet launch to ensure Ledger's would work on hardened wallets, though it seems it wasn't necessary.
> fix: entitlement issue

- app/hooks/use-delegation-status.ts
> [Download the latest build](https://github.com/hirosystems/desktop-wallet/actions/runs/4718932579)
We used to get a value back from the stacking library that we no longer do (defaults to 0).  Rather than showing the amount that the user allowed to delegate, we show the amount currently locked.
> fix: pooling card amount, closes #1150
